spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    melo.guilhermer: DEBUG