version: '3.7'

services:
  licensingservice:
    image: licenseservice
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
        backend:
            aliases:
              - "licenseservice"
networks:
  backend:
    driver: bridge