server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

# Configura envio de log para o zipkin
zipkin:
  baseUrl: zipkin:9411


spring:
  # Configura para que 100% dos logs sejam enviados para o zipkin
  sleuth:
    sampler:
      percentage: 1
  cloud:
    # Habilita a criação de rotas baseado nos serviços registrados com o service discovery
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: organization-service
          uri: lb://organization-service

          predicates:
            - Path=/organization/**

          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
            # Possibilita que o header Authentication passe para os serviços atrás do gateway
            - RemoveRequestHeader= Cookie,Set-Cookie
    compatibility-verifier:
      enabled: false