spring:
  application:
    name: config-server
  profiles:
    # Usando native porque armazenará as configurações no sistema de arquivos
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8071